### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by speleo3**
Works with Python 2 and 3

### CODE REVIEW

**Comment by Moini** [comment]
Hi Thomas :) Thank you!

Seems I forgot to close this repo... would you mind making another merge request on gitlab?

I moved everything over there when Inkscape started to use it: 
https://gitlab.com/Moini/inkscape-extensions-multi-bool/

So sorry :cry:

**Comment by Moini** [comment]
Oh, and: where did you find the link to this? Seems I need to update that, too.

**Comment by Moini** [comment]
I found it on the inkscape.org website - fixed link.

**Comment by speleo3** [comment]
Moved to https://gitlab.com/Moini/inkscape-extensions-multi-bool/merge_requests/1

@Moini I suggest you add a `moved to <new gitlab URL>` note to the github repo and then archive it.

**Comment by Moini** [comment]
Yes, already done for the other extension on here. I wanted to wait, in case you'd prefer to have me do the merge, and so we could comment here. Thank you!

Archiving now.

**Pull request closed without merging**
